# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ 'dev' ]
  pull_request:
    branches: [ "staging" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure python packages
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade

      - name: Run unit tests workflow/job on databricks
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          python databricks-triggers/unit_tests.py

#       - name: Trigger unit tests to run in databricks
#         uses: databricks/run-notebook@v0
#         with:
#           local-notebook-path: tests/tests_staging.py
#           databricks-host: ${{ secrets.DATABRICKS_HOST }}
#           databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
#           existing-cluster-id: "1130-222406-lee92yy1"
#           run-name: "unit tests for CI"
#           access-control-list-json: >
#             [ { "group_name": "users", "permission_level": "CAN_VIEW" } ]
