name: Update Databricks Repos with Repos API

on:
  push:
    branches:
      - staging

jobs:

  update:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Databricks repo - staging branch
        run: |
          cp config/.netrc ~/.netrc
          echo "Current repository ${{ github.repository }}"
          echo "Current branch ${GITHUB_REF_NAME}"
          curl --netrc -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" -d '{"branch":"staging"}' https://dbc-1f875879-7090.cloud.databricks.com/api/2.0/repos/62254856056833
