name: Update Databricks Repos with Repos API

on:
  push:
    branches:
      - dev


jobs:
  
  build:
  	runs-on: ubuntu-latest
	steps:
		- name: Git checkout
	  	  uses: actions/checkout@v3
		- name: Get updated branch name
	  	  uses: echo "running on branch ${GITHUB_REF##*/}"
