name: Update Databricks Repos with Repos API

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup databricks-cli
      run: |
          python -m pip install --upgrade pip
          pip install databricks-cli --upgrade
    
    - name: Setup successful
      run: echo "Setup successful"
